### PR TITLE
Add Fission testimonial

### PR DESCRIPTION
**Pull request by expede**

### CODE REVIEW

**Review by rebeccaskinner — CHANGES_REQUESTED** [review]
Thanks for the PR! It looks like the logo png needs to be resized to 300x300px. Would you mind resizing it? Otherwise this looks good to me.

**Comment by tomjaguarpaw** [comment]
Currently, as you can see from [the action](https://github.com/haskell-infra/www.haskell.org/actions/runs/1397107418) it looks like the below. Is that what you mean by it needs to be 300x300, @rebeccaskinner?

screenshot

**Comment by expede** [comment]
@rebeccaskinner fixed! Please let me know if you need any other changes

**Comment by tomjaguarpaw** [comment]
Looks better now, thank you!

screenshot

**Review by tomjaguarpaw — APPROVED** [review]

**Review by rebeccaskinner — APPROVED** [review]

**Pull request merged**
