### PR TITLE
Add link to differences between GHC and the language report

### PR DESCRIPTION
**Pull request by noughtmare**
I think it is important for readers of the report to know how GHC differs.

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
Sounds sensible. Could you please move the link to be around "the GHC User's Guide" (and match its punctuation, i.e. "User's" not "User")?  I can see the earlier links use "here" as anchor text, but that's pretty bad practice and I don't want to perpetuate it.

**Comment by noughtmare** [comment]
Hmm... The manuals and guides list includes "GHC User Guide" should that be changed too?

**Comment by tomjaguarpaw** [comment]
Yes, well spotted. Feel free to add that to this PR.

**Comment by noughtmare** [comment]
I see now that it also lists `Cabal User Guide` , `Stack User Guide`, and `Haddock User Guide`. Can I fix those too in this pull request? It's unrelated, but it feels awkward to leave those in.

Also, the Stack User Guide does call itself "User guide": https://docs.haskellstack.org/en/stable/GUIDE/

**Comment by tomjaguarpaw** [comment]
If you want to fix more then please go ahead! However, the text we use should be the same as the way that the guides refer to themselves. Cabal and Stack both seem to use "User Guide" so we should stick to that (despite not actually linking directly to what Stack calls its "User Guide").

**Comment by noughtmare** [comment]
Oh, the link of the cabal guide is www.haskell.org/cabal/users-guide/, so I assumed it would be User's Guide... I'll just change the GHC one then.

**Comment by tomjaguarpaw** [comment]
Ah I see. That link is outdated anyway. It should point to <https://cabal.readthedocs.io/en/3.6/>.

**Comment by tomjaguarpaw** [comment]
Very nice, thank you!

**Review by tomjaguarpaw — APPROVED** [review]

**Comment by tomjaguarpaw** [comment]
We'll need to wait for another committee member to approve too.

**Comment by noughtmare** [comment]
> Ah I see. That link is outdated anyway. It should point to https://cabal.readthedocs.io/en/3.6/.

I think the haskell.org link redirects to that, which is nice because the haskell.org link should be stable even if cabal releases another version or decides to move away from readthedocs.

**Comment by tomjaguarpaw** [comment]
Yes, OK, that seems like a good reason to preserve it.

**Review by TikhonJelvis — APPROVED** [review]
Looks good. Thanks for the PR :)

**Pull request merged**
