### PR TITLE
Revert alternative logo

### PR DESCRIPTION
**Pull request by rhendric**
Six months ago:

‘It would most certainly be temporary...’

### CODE REVIEW

**Review by tomjaguarpaw — APPROVED** [review]
Fine by me

**Comment by MangoIV** [comment]
But why would we revert it?

**Comment by tomjaguarpaw** [comment]
Exactly because [part of the justification for adding it](https://github.com/haskell-infra/www.haskell.org/pull/292#issuecomment-2090806936) was that it would be temporary. It would set a bad precedent to keep something that was explicitly justified on the grounds of being temporary. If people _do_ want to keep it, that's fine, but I think it should go through another proposal process.

(In retrospect I think we ought to have set a time limit on it, after which it would have been "pre-approved" for reversion, absent another vote to keep it.)

**Comment by tomjaguarpaw** [comment]
> I think it's a fun Easter egg so I would say keep it.

I'm inclined to agree actually. It seems fun and I don't think it's doing any harm. But it is up to the people who want to keep it permanently to make such a proposal and advocate for it, otherwise we're going to lose trust in proposals whose proponents claim "this is only temporary".

**Comment by kutyel** [comment]
I think it does not hurt anyone if we keep it and also it shows that the Haskell community still has a nice sense of humour 😉

**Pull request closed without merging**
