### PR TITLE
update books

### LINKED ISSUE #96: add books / reorganize books
I know there's bigger plans here, but for now it would be nice to update the book section under documentation.

In particular, there's at least two "intermediate" books not on the page:

https://leanpub.com/production-haskell
https://www.manning.com/books/haskell-in-depth

Given the number of books on the page it might now also be worthwhile to pull the list apart in to "beginner" and "intermediate" texts in general.

### PR DESCRIPTION
**Pull request by gbaz**
resolves #96 and also deletes dead hayoo link while we're at it.

### CODE REVIEW

**Review by TikhonJelvis — APPROVED** [review]
Looks good to me. Breaking up a big list like this into sections definitely makes it easier to parse.

**Review by tomjaguarpaw — APPROVED** [review]
Great, thanks!

**Comment by tomjaguarpaw** [comment]
For definiteness, let's say I'll merge this on Monday unless anyone else has anything to say in the meantime.

**Comment by tomjaguarpaw** [comment]
Will delete this merged branch in one week unless anyone has a reason to keep it around.

**Pull request merged**
