### PR TITLE
Add #haskell-language-server channel

### PR DESCRIPTION
**Pull request by jneira**

### CODE REVIEW

**Review by rebeccaskinner — APPROVED** [review]
This looks good to me.

**Review by tomjaguarpaw — APPROVED** [review]
Thanks!

(In fact this probably belongs under "Related channels" rather than "Projects using haskell" but I don't mind merging this now and then fixing that up later. Lots of other things on that page need fixing too, like alphabetisation and splitting off the language-specific channels from the "Related channels".)

**Comment by jneira** [comment]
agree, but I was not sure about so I will move to related channels, thanks!

**Comment by jneira** [comment]
I am not used to editing using the web UI in a phone. 😟

**Comment by jneira** [comment]
@tomjaguarpaw ok, i think it is ready to go, thanks!

**Comment by tomjaguarpaw** [comment]
Thanks! There seems to be a problem with the deployment system so it may take a while before this reaches the live site. Feel free to comment on this PR (or contact me directly) if that becomes a problem.

**Pull request merged**
