### PR TITLE
Add Portland Has Skill meetup

### PR DESCRIPTION
**Pull request by kaBeech**
I just founded this meetup and I would like to add it to the community page! 😸

This commit also moves the London Haskell meetup to be in alphabetical order because OCD

### CODE REVIEW

**Review by tomjaguarpaw — APPROVED** [review]
Thanks! We need another approval before merge.

**Review by aaronallen8455 — APPROVED** [review]

**Comment by tomjaguarpaw** [comment]
This is blocked on https://github.com/haskell-infra/www.haskell.org/issues/304

**Comment by tomjaguarpaw** [comment]
This will need to be rebased on `master`. (You can also drop the change to London Haskell, as we're going to remove it: it's no longer active).

**Comment by kaBeech** [comment]
Done! Apologies for the extra London edit, I'll remember to open an issue at most next time. Thank you!

**Comment by tomjaguarpaw** [comment]
It still seems to have a conflict. I'll rebase it myself when I get round to it, unless you get there before me.

**Comment by kaBeech** [comment]
Oh, that was silly. Better?

**Comment by kaBeech** [comment]
Whoops, that was silly. Better?

**Comment by tomjaguarpaw** [comment]
Thanks!

**Pull request merged**
