### PR TITLE
Stephen Diehl pages no longer resolve. Updating to archive.org version.

### PR DESCRIPTION
**Pull request by djoldman**

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
Thanks for this. Before merging we should confirm with Stephen whether these are coming  back in the near future.

**Comment by tomjaguarpaw** [comment]
I've emailed him. I'll report back if I hear anything. Feel free to ping this thread in a week or so if nothing has happened in the meantime.

**Comment by tomjaguarpaw** [comment]
I haven't heard anything back yet.

**Comment by tomjaguarpaw** [comment]
Still no response. Let's apply this PR if I haven't heard in one week.

**Review by TikhonJelvis — APPROVED** [review]
@tomjaguarpaw I assume you still didn't get a reply? We can probably apply this PR then

**Comment by tomjaguarpaw** [comment]
Yes, good idea. Thanks for the nudge.

**Pull request merged**
