### PR TITLE
Haskell company quotes

### PR DESCRIPTION
**Pull request by romefeller**
Inroducing IOHK to the testimonials page.

### CODE REVIEW

**Review by tomjaguarpaw — APPROVED** [review]

**Comment by tomjaguarpaw** [comment]
We might want to ask them to flesh this out more. It's a bit vague.

> when it comes to programming languages work there is no competitor to Haskell.

**Comment by TikhonJelvis** [comment]
I believe a lot of their PL-oriented work is either open source or at least public, right? A quote referencing a specific project or effort would be more effective—"show" rather than "tell".

**Review by rebeccaskinner — APPROVED** [review]
If IOHK is happy with this as their quote, I think it's good. Many of the submissions we got were too long to fit comfortably on the screen, I think this is about the length that I originally had in mind when we started this.

**Comment by romefeller** [comment]
@TikhonJelvis can you merge it?

**Comment by TikhonJelvis** [comment]
Sure, let's go for it. More specific/compelling quotes would be nice, but sounds like it isn't worth the hassle right now. We can revisit this fish the line when it's time to update/refresh the testimonials.

**Pull request merged**
