### PR TITLE
Fix oddly sized logos in testimonials

### PR DESCRIPTION
**Pull request by sekunho**
Read #140 and found out there were some others that could be improved.

IOHK before:

image

IOHK after:

image

e-bot7 before:

image

e-bot7 after:

image

Fission before:

image

Fission after:

image

### CODE REVIEW

**Review by tomjaguarpaw — APPROVED** [review]

**Comment by tomjaguarpaw** [comment]
Fantastic, thank you! Perhaps we want to keep the SVG though, in case we need it in the future?

**Comment by sekunho** [comment]
Alright, I'll add that back in.

**Review by rebeccaskinner — COMMENTED** [review]
I noticed this changes the IOHK logo from a version with text to one without. Is this an official logo they provide? I think the changes look great, and I'm not worried about the resizing on the others since we're not changing the logo, but I don't want to change a companies branding without their permission.

**Comment by tomjaguarpaw** [comment]
In that case, @sekunho can you remove the IOHK change from this PR and make a separate PR for it? We can get this one in whilst we seek confirmation from IOHK.

**Comment by sekunho** [comment]
@rebeccaskinner @tomjaguarpaw Yeah, I detailed this in the commit message https://github.com/haskell-infra/www.haskell.org/pull/173/commits/de3fb38ab86a7509dcf14b8fdafe2f154d695d0f.

> Merely resizing it to fit nicely in a 300x300 resolution wasn't enough
since the logo would be too small, give how wide it is. So I got one
without the text from IOHK's official media kit.
>
> https://iohk.io/en/media-kit/

It's their official logo.

**Comment by tomjaguarpaw** [comment]
OK then, this looks fine. @rebeccaskinner, do you agree?

**Review by rebeccaskinner — APPROVED** [review]
This is looks great to me, thanks for confirming that we're good to use this IOHK logo!

**Comment by rebeccaskinner** [comment]
> OK then, this looks fine. @rebeccaskinner, do you agree?

yep, approved!

**Comment by sekunho** [comment]
Thanks for everyone's time!

**Comment by tomjaguarpaw** [comment]
Thank you for your contribution, @sekunho!

**Pull request merged**
