### PR TITLE
Suggest introductory resource

### PR DESCRIPTION
**Pull request by ffaf1**
As proposed in #155.

### CODE REVIEW

**Review by jaspervdj — APPROVED** [review]

**Comment by tomjaguarpaw** [comment]
Is there an important difference between Fall 16 and Spring 13? [@bitemyapp's guide recommends](https://github.com/bitemyapp/learnhaskell#yorgeys-cis194-course) Spring 13. Is there a reason to choose one over the other?

**Comment by ulysses4ever** [comment]
@nomeata would know.

**Comment by tomjaguarpaw** [comment]
Ah yes, @nomeata was the course instructor. Joachim: could you give us your opinion of what the most appropriate CIS194 course is to link from the haskell.org homepage?

I found [a post about the course](https://www.joachim-breitner.de/blog/705-The_new_CIS-194) on Joachim's blog. It sounds very cool but makes me wonder whether it's out of date now due to changes in CodeWorld.

> The CodeWorld API has evolved, and not all code examples work any more, and some pictures in the lecture notes will stay blank. Sorry for that.

**Comment by nomeata** [comment]
The biggest changes are the first four weeks, which I have re-done based on CodeWorld. Indeed the CIS page is out-of-date, but I have extracted these portions into a stand-alone and maintained tutorial at <https://haskell-via-sokoban.nomeata.de/>.

So maybe link to Spring 13, and additionally somewhere to my tutorial?

**Comment by tomjaguarpaw** [comment]
Thanks. @ffaf1 could you adjust this PR to Spring 13? We can add a link to Joachim's tutorial separately (or you can incorporate it into this PR if you wish).

**Review by tomjaguarpaw — APPROVED** [review]

**Comment by tomjaguarpaw** [comment]
Thanks!

**Pull request merged**
