### PR TITLE
Community: Add Haskell DC

### PR DESCRIPTION
**Pull request by mreed20**
Let's add this one! I talked to the owner of the group on Meetup.com and they're okay with being added to the list.

### CODE REVIEW

**Comment by gwils** [comment]
Can you please alphabetise this under Haskell rather than DC?

**Comment by mreed20** [comment]
@gwils done!

**Comment by mreed20** [comment]
And I haven't used GitHub in a while, but is force pushing now discouraged?

**Comment by gwils** [comment]
No, it just highlights them now. There's no problem.
Thank you for this addition.

**Comment by mreed20** [comment]
Hi,
I just noticed that the change isn't live on the website. Just wanted to let you know in case you weren't aware.

**Comment by TikhonJelvis** [comment]
Thanks for catching that!

I'm not sure why this change has not been deployed yet. I'm going to look into it and see if we can get an updated version of the page up soon.

**Comment by mreed20** [comment]
@TikhonJelvis I see it on the website now, thanks!

**Pull request merged**
