### PR TITLE
haskell-org-committee: merge in content from the wiki

### PR DESCRIPTION
**Pull request by ketzacoatl**
As outlined in #59, there are two pages which describe the Haskell.org committee and it's roles, responsibilities, process, history, etc. One is here on haskell.org, the other is on the wiki at https://wiki.haskell.org/Haskell.org_committee. Both pages appear authoritative, but differ in their content. At the same time, the general consensus is to move content off the wiki (particularly the more "official" content such as this). We would then replace that wiki article with a link to the this page. This is a first attempt which is more of a "bulk import" (or "merge") of the existing content. Note that there are a few places where the differences in content on the haskell.org page and wiki article may seem to be in conflict (or where one does not go as far as the other). These discrepancies and conflicts should be reviewed and updated. Some of the wiki content is more verbose than that on this page, and may still deserve some word-smithing.

A rough list of changes:
* collected the full list of links at the bottom of the page
* move the list of "committee members" a little lower in the page, bumping contact info above
* Included/merged wiki content: process, history and responsibilities content

I can make additional updates to this, but would need feedback on that. cc @tikhonjelvis

---

This is an updated PR, see https://github.com/ketzacoatl/www.haskell.org/pull/1 for the original (which was mistakenly created over there and GH doesn't let me move or update the base repo the PR targets), including @TikhonJelvis's feedback to the original.

This PR attempts to incorporate all of the feedback from that first PR.

### CODE REVIEW

**Review by TikhonJelvis — APPROVED** [review]
Looks great, thanks!

I pushed a tiny formatting tweak (changed code block to block quote), and I think it looks great to merge. I'll ping somebody else on the committee for a second review, then we can merge this, deploy the change and change the Wiki page.

**Comment by TikhonJelvis** [comment]
Once this is merged, we can also do a quick PR updating the list of committee members (addressing #62). I'd like to do that in a separate PR to keep the history easy to navigate.

**Comment by ketzacoatl** [comment]
That sounds great @TikhonJelvis, I look forward to seeing the updates go live.

LMK if you would like assistance updating the list of members, I can tackle that in a separate PR if you like.

**Comment by TikhonJelvis** [comment]
Thanks. That'll be a tiny PR and I figure whoever ends up merging this one can do it right after—I'm just holding off for now because I don't want to think about merge conflicts when I should be going to bed instead :stuck_out_tongue:.

**Review by rebeccaskinner — APPROVED** [review]
This is a great start. I think we have some additional things we'll want to get added here, and hopefully this will kick off some momentum in us doing so.  Thanks for the PR!

**Comment by ketzacoatl** [comment]
Great news, thanks for the collaboration and support along the way  :)

**Comment by ketzacoatl** [comment]
https://wiki.haskell.org/Haskell.org_committee has been updated to drop the content and refer to https://www.haskell.org/haskell-org-committee/ and this PR.

**Comment by SAGARGAUD01** [comment]
Hello sir how can I participate in this.

**Pull request merged**
