### PR TITLE
Add category theory for programmers

### PR DESCRIPTION
**Pull request by mattbaumann**
A good and free resource for an existing programmer, especially written for OOP enthusiasts.

The resource is well written and allows the person to follow the simple and short steps the author takes in order to "adjust" the programmers mindset step by step in order to be willing to throw all of their beloved OOP knowledge overboard.

It is available as a blog under bartoszmilewski.com or as a book under the link. The layouted book can be built from source, printed with the provided PDF's or bought over the link to the repository.

Link to repository: https://github.com/hmemcpy/milewski-ctfp-pdf

### CODE REVIEW

**Comment by gbaz** [comment]
Its a great book, but I don't think its a good resource to learn haskell?

**Comment by mattbaumann** [comment]
I just thought we should not only engage bloody beginners, then there are different types of beginners. Either you are a programming beginner or you are routined in other Langs and don't want to be bored, but are a _haskell beginner_, like me.

1. boredom in some books
2. It was the most understandable I've read so far for my brain at least
3. It's free, reduces the barrier, especially for programmers and students.

**Comment by gbaz** [comment]
I don't think it is a good book for haskell beginners even if they know a lot about other languages. It is a good book for category theory beginners who already know a little FP. That is certainly the intended audience. If someone lands on the haskell homepage, they want to learn the haskell language. The purpose of the book is not to teach that.

**Comment by gbaz** [comment]
(to be clear, I am not writing this as someone who is averse to this material or does not want it available: I am in the acknowledgements of the book)

**Comment by mattbaumann** [comment]
Fair enough, thanks for considering and feedback.

**Pull request closed without merging**
